name: Test this WIP agains the Reactive Feature Pack

on:
  push:
    branches:
      - reactive-port*
  pull_request:
    branches:
      - reactive-port*

jobs:
  wildfly-feature-branch:
    name: Test feature pack

    runs-on: ubuntu-latest

    steps:
      - name: Checkout WildFly
        uses: actions/checkout@v2
        with:
          path: wildfly

      - name: Checkout Feature Pack
        uses: actions/checkout@v2
        with:
          repository: kabir/wildfly-mp-reactive-feature-pack
          ref: development
          path: featurepack

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build WildFly
        run: mvn -B install -DskipTests
        working-directory: wildfly

      - name: Test WildFly
        run: |
          mvn -B install -DallTests -fae -pl testsuite/integration/microprofile,testsuite/integration/microprofile-tck/reactive-messaging,testsuite/integration/microprofile-tck/reactive-streams-operators
        working-directory: wildfly


      - name: Initialise WildFly versions
        # Needed to download everything from Maven to not pollute the output in the next steps
        run: |
          mvn -B help:evaluate -Dexpression=project.version -pl .
          mvn -B help:evaluate -Dexpression=version.org.wildfly.core -pl .
        working-directory: wildfly

      - name: Set WILDFLY_VERSION
        run: |
          TMP="$(mvn help:evaluate -Dexpression=project.version -pl . | grep -v '^\[')"
          echo "::set-env name=WILDFLY_VERSION::${TMP}"
        working-directory: wildfly

      - name: Set WILDFLY_CORE_VERSION
        run: |
          TMP="$(mvn help:evaluate -Dexpression=version.org.wildfly.core -pl . | grep -v '^\[')"
          echo "::set-env name=WILDFLY_CORE_VERSION::${TMP}"
        working-directory: wildfly

      - name: Build and Test feature pack
        run: |
          mvn -B install -fae -Dversion.org.wildfly=${WILDFLY_VERSION} -Dversion.org.wildfly.core=${WILDFLY_CORE_VERSION} -Dqs.test
        working-directory: featurepack

      - name: Initialise Feature Pack version
        # Needed to download everything from Maven to not pollute the output in the next steps
        run:
          mvn help:evaluate -Dexpression=project.version -pl .
        working-directory: featurepack

      - name: Set FEATURE_PACK_VERSION
        run: |
          TMP="$(mvn help:evaluate -Dexpression=project.version -pl . | grep -v '^\[')"
          echo "::set-env name=FEATURE_PACK_VERSION::${TMP}" ;
          echo "TMP ${TMP}"
        working-directory: featurepack

      - name: Show read versions
        run: |
          echo "Feature pack version ${FEATURE_PACK_VERSION}"
          echo "WildFly version ${WILDFLY_VERSION}"
          echo "WildFly Core version ${WILDFLY_CORE_VERSION}"

      - name: Calculate directories to check
        run: |
          SRV_DIR="build/target/wildfly-${WILDFLY_VERSION}-mp-reactive-${FEATURE_PACK_VERSION}"
          echo "::set-env name=BUILD_SERVER_DIR::${SRV_DIR}"
          MODULES_BASE="${SRV_DIR}/modules/system/layers/base"
          echo "::set-env name=UNDERTOW_MODULE_XML::${MODULES_BASE}/org/wildfly/extension/undertow/main/module.xml"
          echo "::set-env name=CONTROLLER_MODULE_XML::${MODULES_BASE}/org/jboss/as/controller/main/module.xml"

      - name: Check versions
        run: |
          if grep -q org.wildfly:wildfly-undertow:${WILDFLY_VERSION} "${UNDERTOW_MODULE_XML}" && grep -q org.wildfly.core:wildfly-controller:${WILDFLY_CORE_VERSION} "${CONTROLLER_MODULE_XML}"; then
            echo "Versions in module.xml files as expected!"
          else
            echo "Versions in module.xml files not as expected!"
            "Expected WildFly version '${WILDFLY_VERSION}' and Core version '${WILDFLY_CORE_VERSION}'"
            echo "Showing contents of ${UNDERTOW_MODULE_XML} and ${CONTROLLER_MODULE_XML}"
            echo "Exiting..."
            exit 1
          fi
        working-directory: featurepack

      - name: Zip Artifacts
        run: zip -R artifacts.zip 'server.log' 'surefire-reports/*.txt' 'surefire-reports/*.xml'

      - uses: actions/upload-artifact@v1
        with:
          name: ci-artifacts-mp-reactive-wf-feature-branch
          path: artifacts.zip
