name: WildFly Cloud Tests Internal

########################################################################
# This is similar to
#  https://github.com/wildfly-extras/wildfly-cloud-tests/blob/main/.github/workflows/wildfly-cloud-tests.yml
# The main changes are
# * It is rolled into one yaml file
# * No inputs to specify other images or run 'manual' jobs
# * No 'manual' jobs
# * Uses a matrix to test the three main images
# * No Openshift tests (the Openshift version is too old)
# * The organisation and branch for the WildFly checkout are determined from pull request event

on:
  pull_request:
  push:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [quay.io/wildfly/wildfly-runtime-jdk11:latest, quay.io/wildfly/wildfly-runtime-jdk17:latest, quay.io/wildfly-snapshots/wildfly-runtime-jdk11-multi-arch:latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Grab runtime image version from matrix
        run: |
          RUNTIME_IMAGE_OVERRIDE=${{matrix.version}}
          echo "Using image: $RUNTIME_IMAGE_OVERRIDE"
          echo "RUNTIME_IMAGE_OVERRIDE=${RUNTIME_IMAGE_OVERRIDE}" >> $GITHUB_ENV


      # Check out wildfly with the information from the PR
      - name: Checkout WildFly
        uses: actions/checkout@v2
        with:
          path: wildfly
          fetch-depth: 1

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Check out the main branch of the cloud tests
      - name: Checkout WildFly Cloud Tests
        uses: actions/checkout@v2
        with:
          path: cloud-tests
          fetch-depth: 1
          repository: 'wildfly-extras/wildfly-cloud-tests'

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build WildFly
        # WildFly main doesn't build without preview at the moment
        # run: mvn -B install -DskipTests -Dskip.preview
        run: mvn -B install -DskipTests
        working-directory: wildfly

      - name: Grab WildFly Version
        id: grab-version
        run: |
          mvn -B help:evaluate -Dexpression=project.version -pl .
          TMP="$(mvn -B help:evaluate -Dexpression=project.version -pl . | grep -v '^\[')"
          echo "version: ${TMP}"
          echo "VERSION_WILDFLY=${TMP}" >> $GITHUB_ENV
        working-directory: wildfly

      - name: Start minikube
        id: minikube
        with:
          driver: docker
          container-runtime: containerd
          cpus: 2
          memory: 4000m
          cni: bridge
        uses: medyagh/setup-minikube@master

      - name: Enable minikube registry
        run: |
          minikube addons enable registry
          kubectl port-forward --namespace kube-system service/registry 5000:80 &

      - name: Run Cloud Tests
        # This builds the provisioned images and runs the main (i.e. non-manual) tests
        # Since the manual tests reuse these images, we don't need to use
        # ${RUNTIME_IMAGE_OVERRIDE} elsewhere.
        run: |
          echo "Runtime image: ${RUNTIME_IMAGE_OVERRIDE}"
          mvn -B install -Pimages -fae -Dversion.wildfly=${VERSION_WILDFLY} ${RUNTIME_IMAGE_OVERRIDE} ${OPENSHIFT_MAVEN_PARAMETERS}
        working-directory: cloud-tests
